theme: jekyll-theme-architect
title: [Sibeesh Venu - An engineer by profession and writer by passion]
description: [I am Sibeesh Venu, an engineer by profession and writer by passion. Microsoft MVP, C# Corner MVP, DZone MVB. ]
